# Drone Insurance {#insurance}

Are you worried about crashing your drone?  While we take a lot of steps to help you fly safely, accidents can happen.  That's what insurance is for.

The UC provides comprehensive insurance coverage **free of charge** for drone operations.  This includes both liability insurance coverage and replacement insurance.

- **Liability insurance** will cover the costs of any damage caused by a drone to another person or property.  If your drone crashes and breaks a window, this is what liability insurance is for.
- **Replacement insurance** will cover the costs of replacing or repairing a damaged, destroyed or lost drone. It has a deductible of $1000.  If your drone crashes into a tree and requires \$4,000 in repairs, you will be reimbursed the actual cost of repair, minus the deductible, for a total of \$3,000.  


## UC UAS Liability Insurance {#liability-insurance}

The University of California has purchased an Unmanned Aircraft System Liability Policy. This policy has a total of \$5 Mil limit including Personal Injury.

Coverage is automatic for UAS activity that meet the following criteria:

- Flight operations are conducted on behalf and sanctioned by the University of California.
- Aircraft weight under 55 lbs (at time of takeoff)
- Flight operations are within Visual Line of Sight
- Flight operations are below 400 ft above ground level.
- Flight operations must be conducted within the United States.


Any UAS activity that do not meet the above criteria or operate outside the above criteria must be reported to and approved by the insurance underwriter in order to be covered. 

> We will follow up with you if your flight operation is not automatically covered and will work with you to ensure coverage.  
>
> On rare occasions, typically on international UAS activity, you or your department may be required to purchase additional coverage.

Any UAS activity that is not approved by a Designated Local Authority or Systemwide Designated UAS Authority is not covered by this liability insurance coverage.

We recommend the use of UC Drones web app to ensure coverage - but please remember that if the Flight is not in the system as "Approved" you are not covered.  

- An approved Project does not grant insurance coverage, you must submit a Flight notification or request to ensure insurance coverage.

### Personally Owned Unmanned Aircraft Used for University Business 
The University of California has extended their UAS liability policy to enable coverage of UAS owned by UC students, staff or faculty used for University Business, including research. Coverage in contingent on compliance with the policy and procedures on UAS usage. This coverage is not intended to cover student organizations or 3rd Party vendors or contractors. 

### Coverage for Campus Police
The University of California has extended their UAS liability policy to enable coverage of UAS by Campus Police. All coverage is contingent on the UAS activity being sanctioned by the UC.

Any UAS activity that is not approved by a Designated Local Authority or Systemwide Designated UAS Authority is not covered by this liability insurance.

## UC UAS Replacement Insurance {#hull-insurance}

Physical damage to a UAS is covered under a blanket policy issued by the University’s captive insurance company, Fiat Lux Risk and Insurance Company

-	Coverage applies in flight only when an approved flight plan is filed in accordance with UC UAS Policy, including the UC Drone web app or other means of compliance.  
-	Coverage is limited to $25,000 for Unmanned Aircrafts
-	Payload is covered separately and not included within this limit
-	$1,000 deductible applies to each and every loss (including payload)
- Coverage additionally applies in the event of theft, vandalism, fire and other perils in accordance to the UC Property Insurance Program.
-	In the event of a loss, please report to campus risk management.  

This physical damage coverage does not extend to personally owned-UAS used for University Business.  **Only UAS owned by the University of California are covered.**

### Filing a Claim
To file a claim, contact your campus Risk Manager.  Please prepare the following:

-	Copy of the post-flight report (through UC Drones or other means of compliance)
-	Photographs of damaged equipment
-	Copy of original purchase invoice
-	Copy of invoice to ship the equipment back the manufacturer 
-	Copy of repair invoice, if repairable 
-	Copy of replacement quote, if not repairable

__Ensure your coverage__

-	Attach a copy of your UAS invoice to your UAS registration in UC Drones
-	Make sure you file your Flight Requests
-	For recurrent or on-going activity, create a Project application but don’t forget to add flights before you head out.
-	After an incident, make sure you take pictures of the damage and file a post-flight report.  Add as much details as possible.