# LAANC Authorization {#ch-LAANC}

In order to get FAA authorization to fly in controlled airspace, you typically will need to file a request through a system called "LAANC"

- If you plan on flying below the Facility Map altitude maximum, authorization will be instantaneous.
- If you want to request flying above the Facility Map altitude maximum, you'll need a Part 107 license and you'll need to make a safety case within your request.  Flight requests are automatically denied if they have not been resolved 24 hours prior to flight, so we recommend filing a request at least 1 week in advance.

## Using AirMap

One of our favorite programs to use for simple and free airspac authorizations is AirMap.  The process is relatively straightfoward.  Create an account, input your pilot and aircraft information, then find a place to fly.  Point to a spot on the map, draw a polygon or even just a line to describe your flight area then submit your flight plan.  It'll go straight to the FAA, or if manual approval by the tower is necessary, it'll go straight to the tower.  

For more information on how to use Airmap, check out their support information here:

[How to apply for Authorization](https://support.airmap.com/hc/en-us/articles/360030924511-How-to-apply-for-Authorization)


## Tips & Tricks

- **Need to draw a polygon using a satellite map?**

    Try this:
    - Go to https://geoman.io/geojson-editor and draw your polygon with satellite map on.  Export to a GeoJSON text file
    - Upload the GeoJSON file to Airmap using the ‘cloud’ button underneath the polygon.
    - The outline should now cover the right area and you file as normal

