# Top 10 Safety Tips {#ch-tips}

Good pilots aren't born, they are forged with training, practice and experience.  When starting on your drone journey, follow these 10 tips for being a safe pilot.

1. **Practice** - There is no substitute for experience.  Gain experience by practicing flying your drone, conducting data collection missions, and flight planning.  Get familiar with your equipment and processes.
2. **Write Everything Down** - Keeping records can help you maintain your equipment, monitor for unsafe practices and keep you on track.  Things to track: battery usage, weather conditions, equipment use/damage, software versions.
3. **Make Checklists and Use Them** - Nothing derails a flight mission like forgetting an item or a step.  Make a checklist for planning a mission, make a checklist for packing your equipment, make a checklist for preflight inspections and any other process you may have. 
4. **Always Keep an Eye on the Weather** - Experienced field researchers know that weather reports are only a suggestion.  Conditions in the field may change dramatically and can turn a good flying day to a disaster.
5. **Bring a friend or two** - Between juggling a flight controller, operating a payload, monitoring weather conditions and scanning for intruding air traffic, it can be taxing to try to do it all at an appropriate level.  Bring some help to make sure everything goes smoothly.
6. **Bring backups or replacement parts** - Many operators will bring spare propellers or batteries to their flight missions, but don’t forget about other supporting equipment such as cables, landing gear, radios or antennas.  Make sure backup parts are on your pre-departure checklist.
7. **Choose appropriate flight locations** - When you choose a location to fly at, make sure you’re aware of all the hazards.  Look for indicators of hidden hazards like rolling hills or high tree lines that create turbulence, or low visibility hazards such as power-lines or towers that interfere with radio systems.  Be aware that you as the pilot are responsible of ensuring the safety of all persons on the ground, whether you can see them or not.
8. **Set boundaries for go/no-go situations and stick to them** - Deciding when to fly and when not to fly should not be an ambiguous decision.  Don’t let external pressures push you to make unsafe decisions.
9. **If something isn’t right, stop immediately** - Nothing fixes itself in the air.  If something doesn’t sound right on the ground during pre-flight checks, don’t fly.  If the weather changes to an unsafe condition, land as soon as it is safe.
10. **Pause and consider all the risks before you fly** - Damage to your aircraft is only one of many aspects to consider.  Consider the payload, consider potential damage to other’s property, consider secondary effects such as causing an auto accident when your aircraft crashes in the middle of a road.  
